type Poll @aws_api_key @aws_cognito_user_pools {
  pollId: ID!
  hostId: String!
  question: String!
  options: [String!]!
  voteCounts: AWSJSON!
  status: String!
  createdAt: AWSTimestamp!
}

type Query {
  getPoll(pollId: ID!): Poll
  listMyPolls: [Poll!]!
    @aws_cognito_user_pools
}

type Mutation {
  createPoll(question: String!, options: [String!]!): Poll!
    @aws_cognito_user_pools
  submitVote(pollId: ID!, option: String!, voterId: String!): Poll!
  closePoll(pollId: ID!): Poll!
    @aws_cognito_user_pools
}

type Subscription {
  onVoteUpdate(pollId: ID!): Poll
    @aws_subscribe(mutations: ["submitVote"])
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}